server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: eddi
    password: eddi@123
    #url: jdbc:mysql://localhost:3306/travelers_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    #username: teamproject
    #password: teamproject
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'update'

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 255506665333-bhj01vifq76veaevhrc140lds8b761dl.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:7777/login/oauth2/code/google
            scope: profile, email

          naver:
            client-id: wObiYFOd0inFfRqiThxw
            client-secret: E8C3kDFS5A
            redirect-uri: http://localhost:7777/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:  mobile, name, email
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 reponse라는 키값으로 네이버가 리턴해줌

  session:
    timeout: 12096000
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

logging:
  level:
    root: info
    com.psc.sample: debug